name: build-check
on:
  push:
    branches-ignore:
      - main

jobs:
  build-check:
    name: build-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm ci
          npm run build
